// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMgb-ba1dGHQpP9DbUP-Yk1mmCiTEvZFg',
    appId: '1:745585172447:web:c82b7c9d485c6e7dfb6e6a',
    messagingSenderId: '745585172447',
    projectId: 'mobilsinavapp',
    authDomain: 'mobilsinavapp.firebaseapp.com',
    storageBucket: 'mobilsinavapp.firebasestorage.app',
    measurementId: 'G-H777JTMSC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw--PuGVSaR0Be2Z3zZg4j1GLwkxaRDPk',
    appId: '1:745585172447:android:313bb7e3c9738c6cfb6e6a',
    messagingSenderId: '745585172447',
    projectId: 'mobilsinavapp',
    storageBucket: 'mobilsinavapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9Q3yYKWm7qZ22-DWvPjWopSo-crrwEA',
    appId: '1:745585172447:ios:fb93947ec3dbdc06fb6e6a',
    messagingSenderId: '745585172447',
    projectId: 'mobilsinavapp',
    storageBucket: 'mobilsinavapp.firebasestorage.app',
    iosBundleId: 'com.example.mobilSinavApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9Q3yYKWm7qZ22-DWvPjWopSo-crrwEA',
    appId: '1:745585172447:ios:fb93947ec3dbdc06fb6e6a',
    messagingSenderId: '745585172447',
    projectId: 'mobilsinavapp',
    storageBucket: 'mobilsinavapp.firebasestorage.app',
    iosBundleId: 'com.example.mobilSinavApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMgb-ba1dGHQpP9DbUP-Yk1mmCiTEvZFg',
    appId: '1:745585172447:web:ebff0442cf40b3effb6e6a',
    messagingSenderId: '745585172447',
    projectId: 'mobilsinavapp',
    authDomain: 'mobilsinavapp.firebaseapp.com',
    storageBucket: 'mobilsinavapp.firebasestorage.app',
    measurementId: 'G-FFJKKQ8YHP',
  );
}
